name: Deploy to GCP using Docker Hub

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: "us-central1"
  BACKEND_SERVICE_NAME: "automodeler-backend"
  FRONTEND_SERVICE_NAME: "automodeler-frontend"
  # Set your Docker Hub image names here
  DOCKER_IMAGE_BACKEND: bikashyin/automodeler-backend
  DOCKER_IMAGE_FRONTEND: bikashyin/automodeler-frontend


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image to Docker Hub
        run: |
          docker build -t $DOCKER_IMAGE_BACKEND:latest ./backend
          docker push $DOCKER_IMAGE_BACKEND:latest

      - name: Build and push frontend image to Docker Hub
        run: |
          docker build -t $DOCKER_IMAGE_FRONTEND:latest ./frontend
          docker push $DOCKER_IMAGE_FRONTEND:latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Backend to Cloud Run from Docker Hub
        run: |
          gcloud run deploy $BACKEND_SERVICE_NAME \
            --image=$DOCKER_IMAGE_BACKEND:latest \
            --platform=managed \
            --region=$REGION \
            --allow-unauthenticated

      - name: Deploy Frontend to Cloud Run from Docker Hub
        run: |
          gcloud run deploy $FRONTEND_SERVICE_NAME \
            --image=$DOCKER_IMAGE_FRONTEND:latest \
            --platform=managed \
            --region=$REGION \
            --allow-unauthenticated \
            --set-env-vars="NEXT_PUBLIC_API_URL=$(gcloud run services describe $BACKEND_SERVICE_NAME --platform=managed --region=$REGION --format='value(status.url)')"